apiVersion: v1
kind: Service
metadata:
  name: mario-service-nodeport
  namespace: default 
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
  - nodePort: 30333
    port: 80
    targetPort: 80
  selector:
    app: mario
  sessionAffinity: None
  type: NodePort
